services:
  backend:
    image: kusho_backend:latest
    ports:
      - "8080:80"
    environment:
      - ENVIRONMENT="prod"
      - KUSHO_FRONTEND_URL="https://op.kusho.dev"
      - KUSHO_BACKEND_URL="https://op-be.kusho.dev"
      - KUSHO_LLM_PROVIDER="openai"
      - KUSHO_MYSQL_USERNAME="root"
      - KUSHO_MYSQL_PASSWORD="password"
      - KUSHO_MYSQL_HOST="127.0.0.1"
      - KUSHO_MYSQL_PORT=3306
      - KUSHO_MYSQL_DB="testing"
      - KUSHO_REDIS_HOST="127.0.0.1"
      - KUSHO_REDIS_PORT=6379
      - KUSHO_REDIS_SSL="false"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=kusho
      - MYSQL_PASSWORD=helloworld
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kusho", "-phelloworld" ]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  worker:
    image: kusho_worker:latest
    command: rq worker --url redis://redis:6379
    environment:
      - ENVIRONMENT="prod"
      - KUSHO_FRONTEND_URL="https://op.kusho.dev"
      - KUSHO_BACKEND_URL="https://op-be.kusho.dev"
      - KUSHO_LLM_PROVIDER="openai"
      - KUSHO_MYSQL_USERNAME="root"
      - KUSHO_MYSQL_PASSWORD="password"
      - KUSHO_MYSQL_HOST="127.0.0.1"
      - KUSHO_MYSQL_PORT=3306
      - KUSHO_MYSQL_DB="testing"
      - KUSHO_REDIS_HOST="127.0.0.1"
      - KUSHO_REDIS_PORT=6379
      - KUSHO_REDIS_SSL="false"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  frontend:
    image: kusho_frontend:latest
    ports:
      - "5173:5173"
    environment:
      - KUSHO_BACKEND_URL="https://op-be.kusho.dev"
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
