apiVersion: batch/v1
kind: CronJob
metadata:
  name: kusho-jobs
spec:
  schedule: "*/10 * * * *" # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kusho-jobs
            image: registry.digitalocean.com/kusho-cs-on-prem/kusho_backend:1.0
            command: ["/bin/sh", "-c", "while true; do python3 jobs/test_cases_generation.py prod; sleep 10; done"]
            envFrom:
            - configMapRef:
                name: kusho-config
            - secretRef:
                name: kusho-secrets
          restartPolicy: OnFailure
