apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusho-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kusho-backend
  template:
    metadata:
      labels:
        app: kusho-backend
    spec:
      containers:
      - name: kusho-backend
        image: registry.digitalocean.com/kusho-cs-on-prem/kusho_backend:1.0
        envFrom:
        - configMapRef:
            name: kusho-config
        - secretRef:
            name: kusho-secrets
        ports:
        - containerPort: 80
