apiVersion: v1
kind: ConfigMap
metadata:
  name: kusho-config
  namespace: {{ .Values.namespace | default "default" }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  KUSHO_FRONTEND_URL: {{ .Values.secrets.KUSHO_FRONTEND_URL | quote }}
  KUSHO_BACKEND_URL: {{ .Values.secrets.KUSHO_BACKEND_URL | quote }}
  KUSHO_LLM_PROVIDER: {{ .Values.secrets.KUSHO_LLM_PROVIDER | quote }}
  KUSHO_MYSQL_HOST: {{ .Values.secrets.KUSHO_MYSQL_HOST | quote }}
  KUSHO_MYSQL_PORT: {{ .Values.secrets.KUSHO_MYSQL_PORT | quote }}
  KUSHO_MYSQL_DB: {{ .Values.secrets.KUSHO_MYSQL_DB | quote }}
  KUSHO_REDIS_HOST: {{ .Values.secrets.KUSHO_REDIS_HOST | quote }}
  KUSHO_REDIS_PORT: {{ .Values.secrets.KUSHO_REDIS_PORT | quote }}
  KUSHO_REDIS_SSL: {{ .Values.secrets.KUSHO_REDIS_SSL | quote }}
  KUSHO_AWS_REGION: {{ .Values.secrets.KUSHO_AWS_REGION | quote }}
  KUSHO_AWS_BEDROCK_REGION: {{ .Values.secrets.KUSHO_AWS_BEDROCK_REGION | quote }}
  KUSHO_AWS_EXPORTS_BUCKET_NAME: {{ .Values.secrets.KUSHO_AWS_EXPORTS_BUCKET_NAME | quote }}
  KUSHO_KINDE_DOMAIN: {{ .Values.secrets.KUSHO_KINDE_DOMAIN | quote }}
  KUSHO_POSTHOG_URL: {{ .Values.secrets.KUSHO_POSTHOG_URL | quote }}
