apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusho-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: kusho-backend
  template:
    metadata:
      labels:
        app: kusho-backend
    spec:
      imagePullSecrets:
      - name: kusho-registry-secret
      containers:
      - name: kusho-backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kusho-config
        - secretRef:
            name: kusho-secrets
      
