apiVersion: batch/v1
kind: CronJob
metadata:
  name: kusho-jobs
  namespace: {{ .Values.namespace | default "default" }}
spec:
  schedule: "{{ .Values.cronJobs.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: kusho-registry-secret
          containers:
          - name: kusho-jobs
            image: {{ .Values.backend.image }}
            imagePullPolicy: Always
            command: ["/bin/sh", "-c", "while true; do python3 jobs/test_cases_generation.py prod; sleep 10; done"]
            env:
            - name: PYTHONPATH
              value: "/app"
            envFrom:
            - configMapRef:
                name: kusho-config
            - secretRef:
                name: kusho-secrets
          restartPolicy: OnFailure
