apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusho-rqworker
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.rqWorker.replicas }}
  selector:
    matchLabels:
      app: kusho-rqworker
  template:
    metadata:
      labels:
        app: kusho-rqworker
    spec:
      imagePullSecrets:
      - name: kusho-registry-secret
      containers:
      - name: kusho-rqworker
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        command: [
            "rq",
            "worker",
            "--with-scheduler",
            "--url",
            "{{ .Values.secrets.KUSHO_REDIS_PROTOCOL }}://{{ .Values.secrets.KUSHO_REDIS_HOST }}:{{ .Values.secrets.KUSHO_REDIS_PORT }}",
            "-c",
            "rq_sentry"
        ]
        envFrom:
        - configMapRef:
            name: kusho-config
        - secretRef:
            name: kusho-secrets
