apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusho-backend
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: kusho-backend
  template:
    metadata:
      labels:
        app: kusho-backend
    spec:
      imagePullSecrets:
      - name: kusho-registry-secret
      containers:
      - name: kusho-backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"     # Requesting 2 vCPUs
            memory: "4Gi" # Requesting 4GB RAM
          limits:
            cpu: "4"     # Max limit of 4 vCPUs
            memory: "8Gi" # Max limit of 8GB RAM
        envFrom:
        - configMapRef:
            name: kusho-config
        - secretRef:
            name: kusho-secrets
      
