apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kusho-backend-ingress
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ split "://" .Values.secrets.KUSHO_BACKEND_URL | last }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kusho-backend-service
                port:
                  number: 80
