apiVersion: v1
kind: Secret
metadata:
  name: kusho-registry-secret
  namespace: {{ .Values.namespace | default "default" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
