apiVersion: v1
kind: Secret
metadata:
  name: kusho-secrets
type: Opaque
data:
  KUSHO_MYSQL_USERNAME: {{ .Values.secrets.KUSHO_MYSQL_USERNAME | default "" | b64enc }}
  KUSHO_MYSQL_PASSWORD: {{ .Values.secrets.KUSHO_MYSQL_PASSWORD | default "" | b64enc }}
  KUSHO_SENDGRID_API_KEY: {{ .Values.secrets.KUSHO_SENDGRID_API_KEY | default "" | b64enc }}
  KUSHO_AWS_ACCESS_KEY_ID: {{ .Values.secrets.KUSHO_AWS_ACCESS_KEY_ID | default "" | b64enc }}
  KUSHO_AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.KUSHO_AWS_SECRET_ACCESS_KEY | default "" | b64enc }}
  KUSHO_SENTRY_DSN: {{ .Values.secrets.KUSHO_SENTRY_DSN | default "" | b64enc }}
  KUSHO_KINDE_CLIENT_ID: {{ .Values.secrets.KUSHO_KINDE_CLIENT_ID | default "" | b64enc }}
  KUSHO_KINDE_CLIENT_SECRET: {{ .Values.secrets.KUSHO_KINDE_CLIENT_SECRET | default "" | b64enc }}
  KUSHO_KINDE_CODE_VERIFIER: {{ .Values.secrets.KUSHO_KINDE_CODE_VERIFIER | default "" | b64enc }}
  KUSHO_OPENAI_ORG_ID: {{ .Values.secrets.KUSHO_OPENAI_ORG_ID | default "" | b64enc }}
  KUSHO_OPENAI_API_KEY: {{ .Values.secrets.KUSHO_OPENAI_API_KEY | default "" | b64enc }}
  KUSHO_PINECONE_ASSISTANT_NAME: {{ .Values.secrets.KUSHO_PINECONE_ASSISTANT_NAME | default "" | b64enc }}
  KUSHO_PINECONE_ASSISTANT_API_KEY: {{ .Values.secrets.KUSHO_PINECONE_ASSISTANT_API_KEY | default "" | b64enc }}
  KUSHO_POSTHOG_API_KEY: {{ .Values.secrets.KUSHO_POSTHOG_API_KEY | default "" | b64enc }}
  KUSHO_MAILCHIMP_API_KEY: {{ .Values.secrets.KUSHO_MAILCHIMP_API_KEY | default "" | b64enc }}
  KUSHO_MAILCHIMP_SERVER: {{ .Values.secrets.KUSHO_MAILCHIMP_SERVER | default "" | b64enc }}
  KUSHO_MAILCHIMP_KUSHO_AUDIENCE_ID: {{ .Values.secrets.KUSHO_MAILCHIMP_KUSHO_AUDIENCE_ID | default "" | b64enc }}
