apiVersion: v1
kind: Secret
metadata:
  name: kusho-secrets
type: Opaque
data:
  MYSQL_USERNAME: {{ .Values.secrets.MYSQL_USERNAME | default "" | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | default "" | b64enc }}
  SENDGRID_API_KEY: {{ .Values.secrets.SENDGRID_API_KEY | default "" | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | default "" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | default "" | b64enc }}
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN | default "" | b64enc }}
  KINDE_CLIENT_ID: {{ .Values.secrets.KINDE_CLIENT_ID | default "" | b64enc }}
  KINDE_CLIENT_SECRET: {{ .Values.secrets.KINDE_CLIENT_SECRET | default "" | b64enc }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | default "" | b64enc }}
  KUSHO_PINECONE_ASSISTANT_NAME: {{ .Values.secrets.KUSHO_PINECONE_ASSISTANT_NAME | default "" | b64enc }}
  KUSHO_PINECONE_ASSISTANT_API_KEY: {{ .Values.secrets.KUSHO_PINECONE_ASSISTANT_API_KEY | default "" | b64enc }}
  KUSHO_POSTHOG_API_KEY: {{ .Values.secrets.KUSHO_POSTHOG_API_KEY | default "" | b64enc }}
