apiVersion: v1
kind: Service
metadata:
  name: kusho-frontend-service
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: kusho-frontend
  ports:
    - protocol: TCP
      port: 80     # The service port
      targetPort: 80  # The container's port in the Pod
  type: ClusterIP
