environment: "production"

namespace: "default"

backend:
  image: "registry.digitalocean.com/kusho-cs-on-prem/kusho_backend:1.3"
  replicas: 1

frontend:
  image: "registry.digitalocean.com/kusho-cs-on-prem/kusho_frontend:1.2"
  replicas: 1

rqWorker:
  replicas: 1

cronJobs:
  schedule: "*/10 * * * *"

secrets:
  ENVIRONMENT: ""
  KUSHO_FRONTEND_URL: ""
  KUSHO_BACKEND_URL: ""
  KUSHO_LLM_PROVIDER: ""
  KUSHO_MYSQL_USERNAME: ""
  KUSHO_MYSQL_PASSWORD: ""
  KUSHO_MYSQL_HOST: ""
  KUSHO_MYSQL_PORT: ""
  KUSHO_MYSQL_DB: ""
  KUSHO_REDIS_HOST: ""
  KUSHO_REDIS_PORT: ""
  KUSHO_REDIS_SSL: ""
  KUSHO_REDIS_PROTOCOL: ""  # "redis" if ssl is false, "rediss" if ssl is true. need this for rq worker setup
  KUSHO_SENDGRID_API_KEY: ""
  KUSHO_AWS_ACCESS_KEY_ID: ""
  KUSHO_AWS_SECRET_ACCESS_KEY: ""
  KUSHO_AWS_REGION: ""
  KUSHO_AWS_BEDROCK_REGION: ""
  KUSHO_AWS_EXPORTS_BUCKET_NAME: ""
  KUSHO_SENTRY_DSN: ""
  KUSHO_KINDE_DOMAIN: ""
  KUSHO_KINDE_CLIENT_ID: ""
  KUSHO_KINDE_CLIENT_SECRET: ""
  KUSHO_KINDE_CODE_VERIFIER: ""
  KUSHO_OPENAI_ORG_ID: ""
  KUSHO_OPENAI_API_KEY: ""
  KUSHO_PINECONE_ASSISTANT_NAME: ""
  KUSHO_PINECONE_ASSISTANT_API_KEY: ""
  KUSHO_POSTHOG_URL: ""
  KUSHO_POSTHOG_API_KEY: ""
  KUSHO_MAILCHIMP_API_KEY: ""
  KUSHO_MAILCHIMP_SERVER: ""
  KUSHO_MAILCHIMP_KUSHO_AUDIENCE_ID: ""

imagePullSecret:
  # to create case64 encoded dockerconfig json, use this command. TOKEN will be provided during onboarding
  # echo -n '{"auths":{"registry.digitalocean.com":{"username":"<ACCESS_TOKEN>","password":"<ACCESS_TOKEN>"}}}' | base64 -w 0
  dockerconfigjson: "BASE64_ENCODED_DOCKER_CONFIG"

